### ISSUE TITLE
[compare] CategoricalArrays' cut vs MLJModels' discretizer

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/MLJModels.jl#129]
The two seem to provide roughly the same functionality, it would be good to see if `cut` is not somehow faster in which case it should either be preferred  or the relevant code should be copied over here.

**Comment by adarshpalaskar1** [comment]
Hello, I am not exactly sure how to go about this, but I performed the following benchmarks:

1. For 1e5 random data points ` data = rand(100000)`:
```
julia> include("benchmarks/discretizer_bm.jl")
Benchmark for CategoricalArrays.jl cut:
Trial(7.370 ms)
Memory:1.1571197509765625 MiB


Benchmark for MLJModels.jl UnivariateDiscretizer:
Trial(2.282 ms)
Memory:0.1917877197265625 MiB
```

2. For 1e3 random data points ` data = rand(1000)`:
```
julia> include("benchmarks/discretizer_bm.jl")
Benchmark for CategoricalArrays.jl cut:
Trial(26.600 μs)
Memory:0.0243377685546875 MiB


Benchmark for MLJModels.jl UnivariateDiscretizer:
Trial(16.100 μs)
Memory:0.0029754638671875 MiB
```

It seems like MLJModels' discretizer is faster. Is this the correct approach to follow? Are there more cases to consider other than varying the data array size?

**Comment by adarshpalaskar1** [comment]
> Thanks @adarshpalaskar1. I think that answers the question well enough. Great to know we are good to rely on the MLJModels implementation.

Thank you. That's great to hear!
