### ISSUE TITLE
Add JLBoost.jl to registry

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaAI/MLJModels.jl#152]
**Updated**

I am having some issue implementing some MLJ features like [`learn_curve!`], see [Discource post](https://discourse.julialang.org/t/how-to-implement-mlj-models-properly-for-learning-curve/31655)

So I've decided to move the MLJ code to a new package to enable indepedent development so I can push ahead with JLBoost features. 

The new repo is here [MJLJLBoost.jl](https://github.com/xiaodaigh/MLJJLBoost.jl)

**Original Content**

I know that @tlienart will review [JLBoost.jl](https://github.com/xiaodaigh/JLBoost.jl) soon, but opening an issue to keep track and for the sense of accomplishment for me when this issue closes ;)

I have implemented the MLJ for JLBoost.jl interface here
<strike>https://github.com/xiaodaigh/JLBoost.jl/blob/master/src/mlj.jl</strike>
**The new repo is here [MJLJLBoost.jl](https://github.com/xiaodaigh/MLJJLBoost.jl)** with code here https://github.com/xiaodaigh/MLJJLBoost.jl/blob/master/src/mlj.jl

<strike>I am unsure about what to put inside `load_path` so I am sure this is not correct `load_path(::Type{<:JLBoostMLJModel}) = ""`</strike>

I can write some reproducible example of using JLBoost.jl's MLJ interface for easy checking.

**Comment by xiaodaigh** [comment]
@tlienart Please note the updated location of the MLJ interface implementation.

**Comment by ablaom** [comment]
For the record, I have added some comments to the [Discource post](https://discourse.julialang.org/t/how-to-implement-mlj-models-properly-for-learning-curve/31655) mentioned in the lead comment.

**Comment by tlienart** [comment]
I'll review this soon (sorry for not getting to it earlier). One early note is that I'd like to not  have  to  interface with packages that start with MLJ that we  do not explicitly endorse or maintain.

In other words, if you do want to use a  specific package for the interface for some reason, please call it something else, best is of course to just have the interface in your package.

@ablaom what do you think? assuming we make this a rule I'll add it to the readme

**Comment by xiaodaigh** [comment]
What if I rename the package to JLBoost Mlj?

**Comment by tlienart** [comment]
Yeah, anything that's not `MLJ*` would be fine I reckon. Note that you'd be the only package so far with  the interface not linking to  the actual package.  While we  don't really care, note that it makes your actual package less visible because we  will link to the interface (including in the metadata) as if there are issues, that's where people should ask  questions.

**Comment by ablaom** [comment]
https://julialang.slack.com/archives/CC57ZE7EY/p1577739316036900?thread_ts=1576719756.000900&cid=CC57ZE7EY

**Comment by xiaodaigh** [comment]
Just to add here as well, Requires.jl might be a doable solution, but I am not going to consider it until it can do version bounds. It's too dangerous and bad UX if the JLBoost becomes out of sync with MLJ.jl. It's generally better for package management to have them in s separate repository so that updating JLBoost doesn't impact MLJ and vice versa.

**Comment by xiaodaigh** [comment]
FYI. i have renamed the package to JLBoostMLJ.jl and it's registered, so should be there within a week.

https://github.com/xiaodaigh/JLBoostMLJ.jl

**Comment by tlienart** [comment]
Thanks, integrations are currently on hold while discussing https://github.com/alan-turing-institute/MLJ.jl/issues/417; there should be more information and a decision next week

**Comment by ablaom** [comment]
Closing as provider of pkg has archived the packaged and moved on.
