### ISSUE TITLE
DecisionTree struct cleanup

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/MLJModels.jl#177]
Currently  there is:

- `display_depth` (in DTC)
- `pdf_smoothing` (in all  *C)

that are hyperparameters that we added for our convenience rather than actual hyperparameters.

- The first one should be ditched in favour of passing a tree-display function  that can take kwargs
- The second one should be ditched in favour of a more generic transformer step (also the initial  reason it was there has been removed since we're clamping the cross entropy now).

**Comment by ablaom** [comment]
These are now resolved.
