### ISSUE TITLE
Get rid of MLJBase from [deps]

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJModels.jl#264]
Everything that supposedly depends on MLJBase should actually only depend on MLJModelInterface

**Comment by ablaom** [comment]
There is an obstacle here: some MultivariateStats models have `UnivariateFinite` priors, so this is not trivial.

**Comment by OkonSamuel** [comment]
@ablaom. Yeah. But MLJBase would still be needed as a test dependency

**Comment by OkonSamuel** [comment]
Also `MLJBase.@load` and `MLJBase.==` stubs may have to be moved to **MLJModelInterface**

**Comment by ablaom** [comment]
I think MLJBase.==, MLJBase.info are already re-exported from MJLModelInterface.

**Comment by ablaom** [comment]
Then there is now ThreshholdPredictor which uses UnivariateFinite type :-(

**Comment by OkonSamuel** [comment]
> Then there is now ThreshholdPredictor which uses UnivariateFinite type :-(

Yea. This issue would be resolved once https://github.com/alan-turing-institute/MLJBase.jl/issues/416 is addressed

**Comment by ablaom** [comment]
Another issue is that Models uses MLJBase.info_dict in the generation of the model registry.

**Comment by ablaom** [comment]
And `available_name`.
