### ISSUE TITLE
Add EvoLinear.jl to model registry

### ISSUE THREAD

**Issue by jeremiedb** [JuliaAI/MLJModels.jl#481]
I'd like to have [EvoLinear.jl](https://github.com/jeremiedb/EvoLinear.jl) added to the model registry. MLJModelInterface is integrated starting with version v0.3.0.

THe library currently essentially covers the the `gblinear` from XGBoost, that is, linear booster with L1/L2 regularization. 
on 1M x 100 feats, EvoLinear.jl is typically over 2X faster than XGBoost equivalent.

**Comment by ablaom** [comment]
Nice. This is happening about once a week these days as part of docstring updates, so it'll get done then.

**Comment by jeremiedb** [comment]
Completed with #482
