### ISSUE TITLE
Update model registry

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJModels.jl#544]
Waiting for:

- [x] Imbabance 0.1.5
- ~~[ ] BetaML~~ ~~0.10.5~~ or 0.11

which have changed model metadata.

cc @EssamWisam @sylvaticus

**Comment by sylvaticus** [comment]
I would like to change the other model interface too, including for some  their names, in order to make the interface homogeneous under the common submodule 'Bmlj'.. is it now the right moment?

**Comment by ablaom** [comment]
> I would like to change the other model interface too, including for some their names, in order to make the interface homogeneous under the common submodule 'Bmlj'.. is it now the right moment?

I think that when a model name changes, that's definitely breaking. So to minimise breaking changes in BetaML, it might be a good idea to tend to those before the next release. In that case I just proceed with a new model registry update soon and we can do another when you're ready.
