### ISSUE TITLE
FeatureSelector is still exported

### ISSUE THREAD

**Issue by adwasser** [JuliaAI/MLJModels.jl#562]
It looks like the FeatureSelector transformation was moved to a different package in this PR:

https://github.com/JuliaAI/MLJModels.jl/pull/558

But the symbol is still exported

https://github.com/JuliaAI/MLJModels.jl/blob/320a29cbded365ada09183cbb5cba3dd00dd0721/src/MLJModels.jl#L46

which leads to a confusing user error:

```
UndefVarError: `FeatureSelector` not defined
```

**Comment by ablaom** [comment]
Good catch, thanks!
