### ISSUE TITLE
Request to add LaplaceRedux.jl to the MLJ registry

### ISSUE THREAD

**Issue by pasq-cat** [JuliaAI/MLJModels.jl#571]
we at Taija would like to add LaplaceRedux.jl to the MLJ's model registry.
we have written an interface for MLJ [laplaceredux.jl interface](https://github.com/JuliaTrustworthyAI/LaplaceRedux.jl/blob/main/src/mlj_flux.jl),

LaplaceRedux.jl allows to compute the approximated posterior predictive distribution of any model through the Laplace approximation (as explained inhttps://arxiv.org/abs/2106.14806) and grants the users the possibility to compute credible intervals with a low computational overhead. 
the LaplaceRedux.jl package is part of the taija  (Trustworthy Artificial Intelligence in Julia) effort (https://github.com/JuliaTrustworthyAI)  effort.

**Comment by ablaom** [comment]
This looks very interesting, thanks. Just back from leave so it may take a week or two before I can look at this properly. 

Note to self: Uses some non-public API from MLJFlux.

**Comment by ablaom** [comment]
cc @EssamWissam

**Comment by pasq-cat** [comment]
@ablaom here https://github.com/JuliaTrustworthyAI/LaplaceRedux.jl/blob/main/src/direct_mlj.jl thank you for your time

**Comment by ablaom** [comment]
Thanks for this. I can hopefully take another look in the next two weeks. Thanks for your patience.

**Comment by ablaom** [comment]
To do list for @ablaom:

- [ ] Check level=4 integration tests pass
- [ ] Check document strings are compliant
- [ ] Add to the MLJModel registry
- [ ] Add model descriptors for MLJ Model Browser and generate new MLJ docs

**Comment by ablaom** [comment]
@pasq-cat According to the docs for the regressor:

- `X`: any table of input features (eg, a `DataFrame`) whose columns
  each have one of the following element scitypes: `Continuous`,
  `Count`, or `<:OrderedFactor`; check column scitypes with `schema(X)`

However, the `input_scitype` makes no mention of `Count`. Is this a mistake in the docstring or the `input_scitype` declaration?

**Comment by ablaom** [comment]
Can I suggest avoiding unicode subscript characters for hyper-parameter names, as in `μ₀`. So `μ0` or `mu0`  are friendlier. Of course I realize this breaking, unless you provide both options, like this `mu0 = 0.0, μ₀=mu0`.

**Comment by ablaom** [comment]
Okay, I think the issues are now sorted on `master`. Can you please tag a new patch. Then I can go ahead with registration.

**Comment by pasq-cat** [comment]
> Okay, I think the issues are now sorted on `master`. Can you please tag a new patch release. Then I can go ahead with registration.
> 

@pat-alt can you do it? I am working this week and I come home really late.

**Comment by pat-alt** [comment]
Thanks @pasq-cat. I've fixed the remaining things in https://github.com/JuliaTrustworthyAI/LaplaceRedux.jl/pull/135, merged the PR and published a new release: https://github.com/JuliaTrustworthyAI/LaplaceRedux.jl/releases/tag/v1.2.0

@ablaom hopefully this should do this trick? Thanks once again for all your help with this and do let us know if anything else needs to be addressed.

**Comment by ablaom** [comment]
> Thanks once again for all your help 

Your welcome.

There's another model being registered soon, so there may be a small delay - it's less work to do both together.

**Comment by ablaom** [comment]
Thanks for you patience. There is a hiccup at MLJModels with the new version of Julia - something to do with Statistics compats (Julia "bug"). It looks like it will be sorted shortly and then I'll go ahead with your model.

**Comment by ablaom** [comment]
Closed as complete.

**Comment by ablaom** [comment]
Closed as complete.
