### ISSUE TITLE
poorly maintained code,  

### ISSUE THREAD

**Issue by JuanVargas** [JuliaAI/MLJModels.jl#573]
I am struggling to understand the point of offering something so poorly maintained as MLJ.
I will try to be positive and offer  constructive criticism.  

There are so many issues that it has hard to figure where to start. But I will try:

1. Documentation is missing, incorrect, outdated. There are several cases of links to non existing pages, such as https://alan-turing-institute.github.io/MLJ.jl/dev/loading_model_code/#Loading-Model-Code

2.  Code shown in the model browser pages often fails. For example, the package  BetaML, which is shown in one of the tutorials, does not work.

3.  I use Go quite extensively, so I was hoping that Julia, also a modern language, would compare well to GO. Unfortunately that is not the case. When I compare the practice of development and testing in Go versus Julia, it is clear that testing in MLJ  is not a primary consideration. There is "test" subdirectory under the MLJ, but  the code is so incomplete....

4. And then, there is the issue of debugging, which is not specific to MLJ, but, debugging in Julia is so  slow that it is simply useless.

5. I really was hoping to like Julia and use it for serious data science work. Unfortunately working in Julia is more of a pain than a joy,  to the extent that I could not use it for the reasons already expressed, and I will recommend my colleagues to stay away.

**Comment by ablaom** [comment]
@JuanVargas Thank you for your feedback, which is appreciated. 

While there is some criticism of MLJ in this post, there is nothing specific  enough for immediate action, and for this reason I am closing. If you are able to pin down details, as noted below, please feel welcome to open new issues.

Many of your concerns appear to be Julia-generic and I suggest you raise these at Julia Discourse, or some other generic forum.

---

> 1. Documentation is missing, incorrect, outdated. 

It's difficult to take action on such a generalized criticism.
>. There are several cases of links to non existing pages, such as https://alan-turing-institute.github.io/MLJ.jl/dev/loading_model_code/#Loading-Model-Code

Be helpful if you supply a link to the page one which the broken ref appears. 

> 2. Code shown in the model browser pages often fails. For example, the package  BetaML, which is shown in one of the tutorials, does not work.

Which tutorial please?

> 3. I use Go quite extensively, so I was hoping that Julia, also a modern language, would compare well to GO. Unfortunately that is not the case. When I compare the practice of development and testing in Go versus Julia, it is clear that testing in MLJ  is not a primary consideration. There is "test" subdirectory under the MLJ, but  the code is so incomplete....

Probably this is a discussion for another forum, such as Julia Discourse.

> 4. And then, there is the issue of debugging, which is not specific to MLJ, but, debugging in Julia is so  slow that it is simply useless.

I suggest Julia Discourse for a discussion of debuggers
